data:
    dataset: "Ohaze"
    image_size: 64
    channels: 3
    num_workers: 0
    data_dir: ""
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000
    vis_mid: 0

training:
    gpus_list: [0]
    patch_n: 16
    batch_size: 32
    n_epochs: 200000
    n_iters: 2000000
    save_ckpt_freq: 1000
    validation_freq: 1000
    f_type: "exponential"

sampling:
    batch_size: 4
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.000002
    amsgrad: False
    eps: 0.00000001
